Task/39 build test scripts csclsroz 14
Accenture/sfmc-devtools pull request #282
Opened 2022-04-27 10:36 UTC by DougMidgley

# PR details

## What is the purpose of this pull request? (put an "X" next to an item)

_Please delete options that are not relevant._

- [ ] Documentation update
- [ ] Bug fix
- [ ] New metadata support
- [ ] Enhanced metadata
- [ ] Add a CLI option
- [X] Add something to the core
- [ ] Other, please explain:

## What changes did you make? (Give an overview)

Test cases for Query & Data Extension to help improve early detection of issues

## Is there anything you'd like reviewers to focus on?

...

## Checklist

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] ESLint & Prettier are not outputting errors or warnings
- [X] README.md updated (if applicable)
- [X] Release Notes Updates

2022-04-30 20:00 UTC, JoernBerkefeld requested changes
dude - tons of work in this one. my respect! 
nevertheless, got a few things that need clearing up and then a demo (or quick pointer on how to run it) would be in order

2022-04-30 21:44 UTC, DougMidgley commented on test/mockRoot/.mcdev-auth.json
> +        }
obfuscated yes, but can put a full dummy value if you prefer :)

2022-04-30 21:45 UTC, DougMidgley commented on test/dataExtension.test.js
> +describe('retrieve', () => {
npm run test, as per package.json :)

2022-04-30 21:46 UTC, DougMidgley commented on test/mockRoot/deploy/testInstance/testBU/dataExtension/childBU_dataextension_test.dataExtension-meta.json
> +            "FieldType": "Text"
this is real results im getting, so if they need removing, that should be managed in another PR.

2022-04-30 21:46 UTC, DougMidgley commented on test/resources/auth.json
> +        "url": "https://mct0l7nxfq2r988t1kxfy8sc4xxx.auth.marketingcloudapis.com/v2/token",
obfuscated yes, but can put a full dummy value if you prefer :)

2022-04-30 21:50 UTC, DougMidgley commented on lib/metadataTypes/Asset.js
> + * @typedef {Object<string, AssetItem>} AssetMap
seems related to version, reverted version changes resolved this

2022-04-30 21:55 UTC, DougMidgley commented on lib/Retriever.js
> +                console.log(ex);
good catch :)

2022-05-04 19:58 UTC, DougMidgley commented on test/mockRoot/deploy/testInstance/testBU/dataExtension/childBU_dataextension_test.dataExtension-meta.json
> +            "FieldType": "Text"
double check as in deploy

2022-05-04 20:27 UTC, merged